name: Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.elm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json', '**/elm.json') }}
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/30daa988f10.tar.gz
      - uses: cachix/cachix-action@v10
        with:
          name: vanilla-extract-forall
          signingKey: ${{secrets.CACHIX_SIGNIN_KEY}}
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - name: Build Page
        run: nix-shell --run "ciBuild"
      - name: Sync Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist